version: '3'

services:
  server:
    build:
      context: /root/ChatGPT-ChromePlugin/Docker/server
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always

  telegram-bot:
    build:
      context: /root/ChatGPT-ChromePlugin/Docker/bot
    env_file:
      - .env
    depends_on:
      - server
    restart: always